Use tqdm with 1024 instead of 1000 unit scale
allenai/cached_path pull request #12
Opened 2021-09-10 19:55 UTC by bryant1410

Change the `tqdm` progress bar so that the scales are multiple of 1024 instead of 1000. Also use the unit "iB" as in "GiB" to make it unambiguous for the user (see [Binary prefix](https://en.wikipedia.org/wiki/Binary_prefix)).

2021-09-10 20:13 UTC, AkshitaB commented
@bryant1410 Hey, PR looks good. I think running `black` should take care of the failing style check.

2021-09-10 20:13 UTC, AkshitaB requested changes
@bryant1410 Hey, PR looks good. I think running black should take care of the failing style check.

2021-09-10 20:14 UTC, bryant1410 commented
> @bryant1410 Hey, PR looks good. I think running black should take care of the failing style check.

Done

2021-09-14 23:36 UTC, AkshitaB approved these changes

2021-09-14 23:36 UTC, merged